server {
  listen 80;

  location / {
    root   /usr/share/nginx/html;
    index  index.html;
    # This is the magic line that makes React Router work correctly
    try_files $uri /index.html;
  }
}